---
title: "vis_1"
author: "Tong Su"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making our 1sr plot :-)

```{r}
ggplot(weather_df, aes(x=tmin, y=tmax))+
  geom_point()
```


```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax))+
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |>
  ggplot(aes(x=tmin, y=tmax))+
  geom_point()

ggp_weather_scatterplot
```

```{r}
weather_df |>
  filter(is.na(tmax))
```

```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point()
```
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = .3, size = .8)
```
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = .3, size = .8) +
  geom_smooth(se=FALSE)
```

Where you define aesthetics can matter
```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point(aes(color=name),alpha = .3, size = .8) +
  geom_smooth(se=FALSE)
```

use faceting real quick

```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = .3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
```


```{r}
weather_df |>
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha = .3)+
  geom_smooth(se=FALSE)+
  facet_grid(name~.)
```

Let's make a somewhat more interesting scatterplot
```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax, color = name)) +
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax, color = name)) +
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)
```
```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax, color = name, size = prcp)) +
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
```

Write a code chain that starts with weather_df; focuses only on Central Park, converts temperatures to Fahrenheit, makes a scatterplot of min vs. max temperature, and overlays a linear regression line (using options in geom_smooth()).
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |>  #720 rows only central park
  mutate(
    tmax_fahr = tmax * (9 / 5) + 32,
    tmin_fahr = tmin * (9 / 5) + 32) |> 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point(alpha = .5) + 
  geom_smooth(method = "lm", se = FALSE)
```


