---
title: "viz_2"
author: "Tong Su"
date: "2024-10-01"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)
```
Look at color
```{r}
ggp_scatterplot =
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color=name)) + 
  geom_point(alpha = .5) + 
  labs(
    title= "Temperature scatterplot",
    x="Minimum Temp (C)",
    y="Maximum Temp (C)",
    color="Location",
    caption = "Weather data taken from rnoaa package"
  ) +
  viridis::scale_color_viridis(discrete = TRUE)
```

```{r}
ggp_scatterplot +
  theme(legend.position = "bottom")
```

```{r}
ggp_scatterplot +
  theme_bw()
  theme(legend.position = "bottom")
```
Order matters
```{r}
ggp_scatterplot +
  theme(legend.position = "bottom") +
  theme_bw()
```

```{r}
ggp_scatterplot +
  theme(legend.position = "bottom") +
  theme_minimal()
```

```{r}
ggp_scatterplot +
  theme(legend.position = "bottom") +
  theme_classic()
```

New scatterplot

```{r}
weather_df |>
  ggplot(aes(x=date, y=tmax, color=name, size=prcp)) +
  geom_point(alpha = .3) +
  geom_smooth(se=FALSE) + 
  viridis::scale_color_viridis(discrete = TRUE) +
  labs(
    x= "Date",
    y="Maximum Temp (C)",
    title= "Seasonal variance in Max Temp",
    size="Precipitation"
  )+
  theme_minimal()+
  theme(legend.position="bottom")
```

Extra bonus stuff in ggplot

Use different datasets in different 'geom's

```{r}
central_park_df =
  weather_df |>
  filter(name == "CentralPark_NY")

molokai_df =
  weather_df |>
  filter(name == "Molokai_HI")

molokai_df|>
  ggplot(aes(x=date,y=tmax, color=name)) +
  geom_point()+
  geom_line(data = central_park_df)
```
#Multiple panels
```{r}
weather_df |>
  ggplot(aes(x=tmax, fill =name)) +
  geom_density()+
  facet_grid(.~name)
```

```{r}
ggp_tmax_tmin = 
  weather_df |>
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=.3)

ggp_tmax_density = 
  weather_df |>
  ggplot(aes(x=tmax, fill=name)) +
  geom_density(alpha=.3)

ggp_tmax_tmin + ggp_tmax_density
```

```{r}
ggp_tmax_tmin = 
  weather_df |>
  ggplot(aes(x=tmin, y=tmax, color=name)) +
  geom_point(alpha=.3)

ggp_tmax_density = 
  weather_df |>
  ggplot(aes(x=tmax, fill=name)) +
  geom_density(alpha=.3)

ggp_tmax_date=
  weather_df |>
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point()+
  geom_smooth(se=FALSE)


(ggp_tmax_tmin + ggp_tmax_density)/ggp_tmax_date
```

##Data manipulation

```{r}
weather_df |>
  ggplot(aes(x=name, y=tmax, fill=name)) +
  geom_violin(alpha=.5)
```

```{r}
weather_df |>
  mutate(name = forcats::fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA")))|>
  ggplot(aes(x=name, y=tmax, fill=name)) +
  geom_violin(alpha=.5)
```

